name: MYDungeon
main: tw.mayortw.mydungeon.MYDungeon
version: 0.0.1
commands:
  dungeon:
    aliases: dg
    usage: "/<dungeon|dg> <action> [...args]\nSupported actions:\ntest"
    permission: mydungeon.manage
permissions:
  mydungeon.manage:
    default: op