name: MYDungeon
main: tw.mayortw.mydungeon.MYDungeonPlugin
version: 0.0.1
commands:
  dungeon:
    aliases: dg
    usage: "/<dungeon|dg> <portal> <list|(portal-index)>"
    permission: mydungeon.manage
permissions:
  mydungeon.manage:
    default: op
  mydungeon.portal.config:
    description: "To manage the configuration of each portal by right-clicking on it"
    default: op
    