name: MYDungeon
main: tw.mayortw.mydungeon.MYDungeonPlugin
version: 0.0.1
commands:
  dungeon:
    aliases: dg
    usage: "/<dungeon|dg> <action> [...args]\nSupported actions:\n  create"
    permission: mydungeon.manage
permissions:
  mydungeon.manage:
    default: op